name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # replace with the name of your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/Assginment-CI-CD-02
          git pull origin main  # make sure to pull from the correct branch
          # Add any other deployment steps or scripts here
